# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake.exe

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /cygdrive/c/Users/rlc/workspace/ranges

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /cygdrive/c/Users/rlc/workspace/ranges

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest.exe --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	cd /cygdrive/c/Users/rlc/workspace/ranges && $(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/Users/rlc/workspace/ranges/CMakeFiles /cygdrive/c/Users/rlc/workspace/ranges/Exceptions/CMakeFiles/progress.marks
	cd /cygdrive/c/Users/rlc/workspace/ranges && $(MAKE) -f CMakeFiles/Makefile2 Exceptions/all
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/Users/rlc/workspace/ranges/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /cygdrive/c/Users/rlc/workspace/ranges && $(MAKE) -f CMakeFiles/Makefile2 Exceptions/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /cygdrive/c/Users/rlc/workspace/ranges && $(MAKE) -f CMakeFiles/Makefile2 Exceptions/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /cygdrive/c/Users/rlc/workspace/ranges && $(MAKE) -f CMakeFiles/Makefile2 Exceptions/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /cygdrive/c/Users/rlc/workspace/ranges && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
Exceptions/CMakeFiles/exceptions-doc.dir/rule:
	cd /cygdrive/c/Users/rlc/workspace/ranges && $(MAKE) -f CMakeFiles/Makefile2 Exceptions/CMakeFiles/exceptions-doc.dir/rule
.PHONY : Exceptions/CMakeFiles/exceptions-doc.dir/rule

# Convenience name for target.
exceptions-doc: Exceptions/CMakeFiles/exceptions-doc.dir/rule
.PHONY : exceptions-doc

# fast build rule for target.
exceptions-doc/fast:
	cd /cygdrive/c/Users/rlc/workspace/ranges && $(MAKE) -f Exceptions/CMakeFiles/exceptions-doc.dir/build.make Exceptions/CMakeFiles/exceptions-doc.dir/build
.PHONY : exceptions-doc/fast

# Convenience name for target.
Exceptions/CMakeFiles/libexceptions.dir/rule:
	cd /cygdrive/c/Users/rlc/workspace/ranges && $(MAKE) -f CMakeFiles/Makefile2 Exceptions/CMakeFiles/libexceptions.dir/rule
.PHONY : Exceptions/CMakeFiles/libexceptions.dir/rule

# Convenience name for target.
libexceptions: Exceptions/CMakeFiles/libexceptions.dir/rule
.PHONY : libexceptions

# fast build rule for target.
libexceptions/fast:
	cd /cygdrive/c/Users/rlc/workspace/ranges && $(MAKE) -f Exceptions/CMakeFiles/libexceptions.dir/build.make Exceptions/CMakeFiles/libexceptions.dir/build
.PHONY : libexceptions/fast

# Convenience name for target.
Exceptions/CMakeFiles/test_exceptions.dir/rule:
	cd /cygdrive/c/Users/rlc/workspace/ranges && $(MAKE) -f CMakeFiles/Makefile2 Exceptions/CMakeFiles/test_exceptions.dir/rule
.PHONY : Exceptions/CMakeFiles/test_exceptions.dir/rule

# Convenience name for target.
test_exceptions: Exceptions/CMakeFiles/test_exceptions.dir/rule
.PHONY : test_exceptions

# fast build rule for target.
test_exceptions/fast:
	cd /cygdrive/c/Users/rlc/workspace/ranges && $(MAKE) -f Exceptions/CMakeFiles/test_exceptions.dir/build.make Exceptions/CMakeFiles/test_exceptions.dir/build
.PHONY : test_exceptions/fast

Contract.o: Contract.cpp.o
.PHONY : Contract.o

# target to build an object file
Contract.cpp.o:
	cd /cygdrive/c/Users/rlc/workspace/ranges && $(MAKE) -f Exceptions/CMakeFiles/libexceptions.dir/build.make Exceptions/CMakeFiles/libexceptions.dir/Contract.cpp.o
.PHONY : Contract.cpp.o

Contract.i: Contract.cpp.i
.PHONY : Contract.i

# target to preprocess a source file
Contract.cpp.i:
	cd /cygdrive/c/Users/rlc/workspace/ranges && $(MAKE) -f Exceptions/CMakeFiles/libexceptions.dir/build.make Exceptions/CMakeFiles/libexceptions.dir/Contract.cpp.i
.PHONY : Contract.cpp.i

Contract.s: Contract.cpp.s
.PHONY : Contract.s

# target to generate assembly for a file
Contract.cpp.s:
	cd /cygdrive/c/Users/rlc/workspace/ranges && $(MAKE) -f Exceptions/CMakeFiles/libexceptions.dir/build.make Exceptions/CMakeFiles/libexceptions.dir/Contract.cpp.s
.PHONY : Contract.cpp.s

test.o: test.cpp.o
.PHONY : test.o

# target to build an object file
test.cpp.o:
	cd /cygdrive/c/Users/rlc/workspace/ranges && $(MAKE) -f Exceptions/CMakeFiles/test_exceptions.dir/build.make Exceptions/CMakeFiles/test_exceptions.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i
.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	cd /cygdrive/c/Users/rlc/workspace/ranges && $(MAKE) -f Exceptions/CMakeFiles/test_exceptions.dir/build.make Exceptions/CMakeFiles/test_exceptions.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s
.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	cd /cygdrive/c/Users/rlc/workspace/ranges && $(MAKE) -f Exceptions/CMakeFiles/test_exceptions.dir/build.make Exceptions/CMakeFiles/test_exceptions.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... exceptions-doc"
	@echo "... libexceptions"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... test_exceptions"
	@echo "... Contract.o"
	@echo "... Contract.i"
	@echo "... Contract.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /cygdrive/c/Users/rlc/workspace/ranges && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

